// Catches highs that were regenerated by software (an exciter / "HF restoration"
// tool) on top of a source that really died well below Nyquist. The codec-lowpass
// detector in cutoff.ts can't see this: there is no knee (the synthetic energy
// reaches Nyquist) and no rising hump (the fill sits flat, below the music), so the
// spectrum reads as a genuine full-bandwidth taper and grades "good". The tell is
// the fill's shape — a DEAD-FLAT energy shelf, detached well below the body of the
// track, that stops declining and holds level to Nyquist. Natural HF never does
// this: real spectra keep falling through the top octave.
//
// Crucially this runs on FFT-integrated band energy, NOT the biquad-bandpass RMS the
// cutoff pass uses. That biquad warps near Nyquist — it fabricates ~11.6 dB of false
// roll-off on flat white noise — which disguises exactly this flat shelf as a decay.
// A flat-response FFT is the only way to see the shelf for what it is.

import { fft } from './fft'

// The probe runs from here up; 8-10 kHz is the reference body every track keeps
// solid energy in, so the shelf's detachment is read against it.
export const BAND_START_HZ = 8000
export const BAND_WIDTH_HZ = 1000
// The shelf lives in the top octave. Below this, genuine content is still rolling
// off on most tracks, so flatness here would catch healthy tapers too.
const SHELF_START_HZ = 17000
// The 8/9/10 kHz bands; their max normalizes loud and quiet masters alike.
const REFERENCE_BANDS = 3
// How flat the top octave must sit to count as a synthetic shelf. Measured: the
// two reprocessed files span 0.4-0.8 dB across 17-22 kHz; the nearest genuine
// (still-declining) master spans 1.9. 1.3 sits in that gap with ~0.5 dB margin
// either side.
const FLAT_RANGE_DB = 1.3
// The shelf must be clearly below the body to be added fill rather than a bright
// master's real highs — Yulbox (genuine, HF near plateau) sits 7 dB down; the
// reprocessed pair sit 15-19 dB down.
const MIN_DEPTH_DB = 10
// ...but not so far down that it is just an ordinary quiet noise floor above a hard
// codec cut (those are a knee, graded by cutoff.ts). A genuine dark taper measured
// ~30 dB down; capping at 25 keeps the reprocessed pair (≤19) and rejects deep floors.
const MAX_DEPTH_DB = 25

// FFT frame: 16384 at 44.1 kHz gives 2.7 Hz bins — fine enough that a 1 kHz band
// integrates ~370 bins, so the per-band energy is a stable average. 50% overlap.
const FRAME = 16384
const HOP = FRAME / 2

// Blackman-Harris window: its ~-92 dB sidelobes keep the loud low end from leaking
// a false floor into the quiet top octave, which a Hann window's -31 dB sidelobes
// can do — and a leaked floor reads as exactly the flat shelf we hunt for.
function blackmanHarris(n: number): Float64Array {
  const w = new Float64Array(n)
  const a0 = 0.35875
  const a1 = 0.48829
  const a2 = 0.14128
  const a3 = 0.01168
  for (let i = 0; i < n; i++) {
    w[i] =
      a0 -
      a1 * Math.cos((2 * Math.PI * i) / (n - 1)) +
      a2 * Math.cos((4 * Math.PI * i) / (n - 1)) -
      a3 * Math.cos((6 * Math.PI * i) / (n - 1))
  }
  return w
}

// Welch-averaged FFT power folded into 1 kHz bands from 8 kHz up to the last band
// fully below Nyquist, returned as dBFS. The absolute level is irrelevant — the
// detector reads bands against each other — so no window/length normalization is
// applied.
export function bandEnergiesDb(pcm: Float32Array, sampleRate: number): number[] {
  const nyquist = sampleRate / 2
  const bandCount = Math.floor((nyquist - BAND_START_HZ) / BAND_WIDTH_HZ)
  const power = new Float64Array(bandCount)
  if (pcm.length < FRAME) return new Array(bandCount).fill(-Infinity)

  const window = blackmanHarris(FRAME)
  const re = new Float64Array(FRAME)
  const im = new Float64Array(FRAME)
  const binToBand = new Int32Array(FRAME / 2 + 1).fill(-1)
  for (let bin = 0; bin <= FRAME / 2; bin++) {
    const hz = (bin * sampleRate) / FRAME
    const band = Math.floor((hz - BAND_START_HZ) / BAND_WIDTH_HZ)
    if (band >= 0 && band < bandCount) binToBand[bin] = band
  }

  const frames = Math.floor((pcm.length - FRAME) / HOP) + 1
  for (let f = 0; f < frames; f++) {
    const start = f * HOP
    for (let i = 0; i < FRAME; i++) {
      re[i] = pcm[start + i] * window[i]
      im[i] = 0
    }
    fft(re, im)
    for (let bin = 0; bin <= FRAME / 2; bin++) {
      const band = binToBand[bin]
      if (band !== -1) power[band] += re[bin] * re[bin] + im[bin] * im[bin]
    }
  }

  return Array.from(power, (p) => 10 * Math.log10(p + 1e-30))
}

// A codec lowpass read off the flat FFT bands instead of the biquad-bandpass RMS the
// cutoff pass uses. The biquad's wide skirts smear a sharp wall: loud energy below the
// cut leaks up through them, so a ~16 kHz brick wall (a 128–160 kbps MP3 re-encoded as
// FLAC) reads as a gentle ~5 dB taper that slips under cutoff.ts's 6 dB knee and grades
// "Good". The FFT has no skirts, so the same wall shows as a single-band cliff (10.4 dB
// at 15→16 kHz on the reference file). We claim a knee only on that unmistakable shape —
// a drop this steep is a codec ceiling, never the few-dB-per-band slope of a real taper.
const KNEE_DROP_DB = 8
// A codec wall never recovers: everything above stays collapsed. Allowing this much
// rebound past measurement jitter tells a wall from a resonant notch that bounces back.
const KNEE_RECOVERY_DB = 2
// The collapsed plateau above the wall must span at least this many bands, so the
// natural roll-off into Nyquist (a steep final step with nothing above it) is never
// read as a wall.
const KNEE_MIN_BANDS_ABOVE = 2
// ...unless the drop is catastrophic. A fake whose real content walls off mid-band but
// is sprayed with sparse HF transient spikes (Harold Heath - Can You Feel) reads as a
// gentle creep through the spiked bands, then collapses 26→34 dB into the floor only at
// the very top edge — where <2 bands sit above. A drop this deep is never a natural
// taper (dark masters shed ≤14 dB across their last bands), so it trips the knee with a
// single band above. The 20 dB line sits ~6 dB clear of both the worst genuine edge drop
// and the shallowest collapse we must catch.
const KNEE_CATASTROPHIC_DROP_DB = 20

// The source's real ceiling (Hz) when the FFT bands carry a codec lowpass the biquad
// pass missed, or null for a natural spectrum. Returns the last full band before the
// cliff — the same convention as cutoff.ts's knee — so the verdict grades the file on
// where its real bandwidth ends. Non-finite bands (a parse hiccup) are skipped rather
// than compared, matching the flat-shelf pass.
export function detectFftKnee(
  bandsDb: number[],
  startHz: number,
  bandWidthHz: number,
): number | null {
  let kneeIndex = -1
  let maxDrop = KNEE_DROP_DB
  for (let i = 0; i < bandsDb.length - 1; i++) {
    if (!Number.isFinite(bandsDb[i]) || !Number.isFinite(bandsDb[i + 1])) continue
    const drop = bandsDb[i] - bandsDb[i + 1]
    const minBandsAbove = drop >= KNEE_CATASTROPHIC_DROP_DB ? 1 : KNEE_MIN_BANDS_ABOVE
    if (bandsDb.length - 1 - (i + 1) < minBandsAbove) continue
    if (drop < maxDrop) continue
    const ceiling = bandsDb[i + 1] + KNEE_RECOVERY_DB
    if (bandsDb.slice(i + 2).some((b) => b > ceiling)) continue
    maxDrop = drop
    kneeIndex = i
  }
  return kneeIndex === -1 ? null : startHz + kneeIndex * bandWidthHz
}

// Returns the real ceiling (Hz) when the top octave is a flat, detached synthetic
// shelf, or null for a natural spectrum. The cutoff points at the elbow where the
// genuine roll-off meets the shelf — the source's true bandwidth under the fill —
// not at the shelf's reach to Nyquist.
export function detectFlatShelf(
  bandsDb: number[],
  startHz: number,
  bandWidthHz: number,
  nyquistHz: number,
): number | null {
  const shelfStart = Math.round((SHELF_START_HZ - startHz) / bandWidthHz)
  const lastBand = bandsDb.length - 1
  // Need the reference body and a few-band shelf to read a shelf at all.
  if (shelfStart < REFERENCE_BANDS || lastBand - shelfStart < 3) return null
  // The shelf signature is energy held all the way TO Nyquist; if the probed bands
  // stop more than a band short of it, this isn't that case (and the bands array is
  // not the full top-octave it must be).
  if (nyquistHz - (startHz + (lastBand + 1) * bandWidthHz) > bandWidthHz) return null

  const plateau = Math.max(...bandsDb.slice(0, REFERENCE_BANDS))
  const shelf = bandsDb.slice(shelfStart)
  const range = Math.max(...shelf) - Math.min(...shelf)
  const shelfLevel = shelf.reduce((sum, v) => sum + v, 0) / shelf.length
  const depth = plateau - shelfLevel
  if (range > FLAT_RANGE_DB || depth < MIN_DEPTH_DB || depth > MAX_DEPTH_DB) return null

  // Walk the elbow down: bands still within the shelf's flatness belong to the
  // fill, so the real ceiling is the first band below them that rises clear of it.
  let onset = shelfStart
  while (onset - 1 >= REFERENCE_BANDS && bandsDb[onset - 1] - shelfLevel <= FLAT_RANGE_DB) onset--
  return startHz + onset * bandWidthHz
}
